// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9DOiIfrirE8m3Q7JyxloJ84Je-wPpfi8',
    appId: '1:361790869356:web:1fd694695a4509853fed49',
    messagingSenderId: '361790869356',
    projectId: 'flutter-chat-app-d4802',
    authDomain: 'flutter-chat-app-d4802.firebaseapp.com',
    storageBucket: 'flutter-chat-app-d4802.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhaZ22sGEmx3IhQbpVnYlIaVbG2jooNDs',
    appId: '1:361790869356:android:841e3470d8299cc83fed49',
    messagingSenderId: '361790869356',
    projectId: 'flutter-chat-app-d4802',
    storageBucket: 'flutter-chat-app-d4802.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7B7vo0g1ZKvtXzmY3Uf8C4I_oJ9xcNJg',
    appId: '1:361790869356:ios:75f39086afe5ae193fed49',
    messagingSenderId: '361790869356',
    projectId: 'flutter-chat-app-d4802',
    storageBucket: 'flutter-chat-app-d4802.appspot.com',
    iosBundleId: 'com.example.firstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7B7vo0g1ZKvtXzmY3Uf8C4I_oJ9xcNJg',
    appId: '1:361790869356:ios:77302bd5eedcd6ef3fed49',
    messagingSenderId: '361790869356',
    projectId: 'flutter-chat-app-d4802',
    storageBucket: 'flutter-chat-app-d4802.appspot.com',
    iosBundleId: 'com.example.firstApp.RunnerTests',
  );
}
